### ISSUE TITLE
Removing `isLink()` from spec

### ISSUE THREAD

**Issue by vmx** [ipld/interface-ipld-format#17]
This spec is about APIs a format needs to implement in order to be used by the resolver.

I think that `isLink()` is a higher level concept. It doesn't need to be implemented by every format, but can be a function of js-ipld-resolver.

@diasdavid What do you think?

**Comment by daviddias** [comment]
I believe @kumavis proposed this one. I see your point @vmx and agree, it can be done entirely on the main resolver given that an IPLD link is a well known structure. What do you think @kumavis ?
