### ISSUE TITLE
Add `defaultHashAlg` property

### ISSUE THREAD

**Issue by vmx** [ipld/interface-ipld-format#20]
If data is inserted into IPLD you need to specify the format as well as the hash that is used. For many formats there's a default hash (often there's even only a single hash type possible). If a format has such a default has, a property on the resolver called `defaultHashAlg` would be defined.

This way you often won't need to specify the hash type (you might not even know it), but only the format. Examples are:

 - Bitcoin => dbl-sha2-256
 - Git => sha1
 - Zcash => dbl-sha2-256

What do others think of that idea?

**Comment by daviddias** [comment]
👍  Sounds good to me. Is the spec the right place to specify this?

**Comment by vmx** [comment]
I think the spec is the right place to specify it.

**Comment by vmx** [comment]
I've changed the property name to 'defaultHashAlg` to be more consistent.

**Comment by daviddias** [comment]
I like it!
