### ISSUE TITLE
Resolver implementations shouldn't rely on IPFS

### ISSUE THREAD

**Issue by vmx** [ipld/interface-ipld-format#21]
Many of the current IPLD Format implementations expect the encoded binary data to be an IPFS block. Though there's not real need for it, they could just rely on the actual data.

This is a tracking issue to change all current available implementations to follow the spec and rely directly on the binary data.

Implementations that needs that fix are:

 - [x] https://github.com/ipld/js-ipld-dag-pb
 - [x] https://github.com/ipld/js-ipld-dag-cbor
 - [x] https://github.com/ipld/js-ipld-ethereum
 - [x] https://github.com/ipld/js-ipld-git
 - [x] https://github.com/ipld/js-ipld-raw

js-ipld-bitcoin and js-ipld-zcash already follow the spec.

**Comment by vmx** [comment]
The changes were merged, now that all need a new major release. I'm doing that now.

**Comment by vmx** [comment]
@diasdavid Either you give me publish rights to all those pages mentioned above, or do a major release yourself :)

**Comment by daviddias** [comment]
gave you perms to all of them. You will need it more times :)

**Comment by vmx** [comment]
@diasdavid I can't do a release of https://github.com/ipld/js-ipld-dag-pb due to 

```
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least one approved review is required by reviewers with write access.        
To github.com:ipld/js-ipld-dag-pb.git
 * [new tag]         v0.12.0 -> v0.12.0
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:ipld/js-ipld-dag-pb.git'
```

I guess branch protection and Aegir don't play well together.
