### ISSUE TITLE
Implement new `cid(blob, ...)`

### ISSUE THREAD

**Issue by vmx** [ipld/interface-ipld-format#32]
The IPLD Format spec was changed so that `util.cid()` now takes the binary blob and not the deserialized DAG Node as argument (https://github.com/ipld/interface-ipld-format/pull/24).

This is a breaking change and needs to be done on all existing formats. So please don't merge before PRs from all formats are approved. This way things can be merged and released in one go.

Instead of opening an issue on every repository, just let people know on this issue that you're working on it and then link to the PR.

 - [x] https://github.com/ipld/js-ipld-bitcoin
 - [x] https://github.com/ipld/js-ipld-dag-cbor
 - [x] https://github.com/ipld/js-ipld-dag-pb
 - [x] https://github.com/ipld/js-ipld-ethereum
 - [x] https://github.com/ipld/js-ipld-git
 - [x] https://github.com/ipld/js-ipld-raw
 - [x] https://github.com/ipld/js-ipld-zcash

**Comment by richardschneider** [comment]
No need to change https://github.com/ipld/js-ipld-raw, because `util.serialise` is a noop,

**Comment by richardschneider** [comment]
@vmx It looks likes bitcoin, zcash and ethereum all have issues, see https://github.com/ipld/js-ipld-zcash/issues/13.  Until this is resolved, perhaps

- I'll revert the `cid-blob` PRs for dag-cbor, dag-pb and git
- You make releases for all IPLD formats (dag-cbor, dag-pb, git, bitcoin, ethereum and zcash)
- I'll finish `ipld.put` https://github.com/ipld/js-ipld/pull/133
- You release ipld

This means 
- NO breaking changes
- you have time to think about the serializer issue
- a few IPLD issues get to be closed

**Comment by vmx** [comment]
@richardschneider Sounds like a good plan. Let's do this!

**Comment by daviddias** [comment]
@achingbrain I believe this is related to the perf work you have done for dag-pb. Could you confirm?

**Comment by achingbrain** [comment]
That's how I came across it, yes - I don't have any hard numbers on the performance increase it would be though because it hasn't been a bottleneck in the profiling I've been doing - it just looked like a weird bit of code that the docs say should be able to be [refactored to do less work](ipld/js-ipld#180) (though in this case the docs appear to be ahead of the implementation).
