### ISSUE TITLE
Implement `defaultHashAlg` property

### ISSUE THREAD

**Issue by vmx** [ipld/interface-ipld-format#37]
After merging https://github.com/ipld/interface-ipld-format/pull/27 all formats need to implement a `defaultHashAlg` property (see the spec for more information).

See the discussion at ipld/js-ipld#82

Instead of opening an issue on every repository, just let people know on this issue that you're working on it and then link to the PR.

 - [x] https://github.com/ipld/js-ipld-bitcoin
 - [x] https://github.com/ipld/js-ipld-dag-cbor
 - [x] https://github.com/ipld/js-ipld-dag-pb
 - [x] https://github.com/ipld/js-ipld-ethereum
 - [x] https://github.com/ipld/js-ipld-git
 - [x] https://github.com/ipld/js-ipld-raw
 - [x] https://github.com/ipld/js-ipld-zcash

**Comment by richardschneider** [comment]
All changes have been pushed to master!
