### ISSUE TITLE
Converge both implementations together

### ISSUE THREAD

**Issue by daviddias** [ipld/interface-ipld-format#4]
- [ ] ~~s/interface-ipld-format/ipld-format~~ (is this still an issue?)
- [x] s/go-ipld-node/go-ipld-format
- [ ] create go-ipld-node and go-ipld-resolver underneath go-ipld-format
- [ ] update the description in the README to point to the go interfaces as well
- [ ] start describing that "X is an IPLD Format, as it implements the ipld-node and ipld-resolver interfaces (oop way), or makes them available to be used over itself (functional way)"

**Comment by daviddias** [comment]
@Stebalien you are part of this ⛵️ too now :)

**Comment by vmx** [comment]
@Stebalien Do I understand correctly that there isn't really a spec for go-ipld, but the spec is what is in https://github.com/ipfs/go-ipld-format?

**Comment by Stebalien** [comment]
That's the interface definition, yes. There's really no point in having a "spec" given that interface definitions can be enforced by the compiler.

**Comment by vmx** [comment]
This repo is very JS specific I hope at one point we can start converging, but for now I think we should concentrate on having a great API for the JS world. Hence closing this issue.
