### ISSUE TITLE
How to return a partially resolved IPLD link from a custom resolver?

### ISSUE THREAD

**Issue by joeltg** [ipld/interface-ipld-format#42]
Hello!
I'm playing with writing my own IPLD format and want to be able to link back to the greater IPLD world after partially resolving a path. 
- What should I pass to the callback in `resolver.resolve` to do this? A CID instance? A base58 CID string? The API says "IPLD Link" but I'm not sure what that means.
- If `remainderPath` is empty, how does IPLD decide if the value is a link (and will return the result of `resolve(<link>, "/")`) or if the value should be returned directly?

**Comment by vmx** [comment]
> What should I pass to the callback in `resolver.resolve` to do this? A CID instance? A base58 CID string? The API says "IPLD Link" but I'm not sure what that means.

Although the [IPLD Spec](https://github.com/ipld/specs/blob/b2108a1396c2dc0b71dc2c1fe4ceae86e4a96834/IPLD.md) is outdated, it still contains information about what an "IPLD Link" is. In JSON it's represented as `{"/": <base58-encoded-CID-string>}`.




> If `remainderPath` is empty, how does IPLD decide if the value is a link (and will return the result of `resolve(<link>, "/"))` or if the value should be returned directly?

If `value['/'] !== undefined` it's a link.
