### ISSUE TITLE
Proposal: Move resolver to use CID instances for links

### ISSUE THREAD

**Issue by mikeal** [ipld/interface-ipld-format#44]
The current API for `resolver.resolve(binaryBlob, path, callback)` calls for us to return `{'/': baseEncodedCID}`.

Now that we're moving to returning `CID` instances in the serializers it would be better to return instances here as well since the majority of the time, possibly *all* the time, we end up just parsing this baseEncodedCID back into a `CID` instance.

**Comment by vmx** [comment]
All IPLD Formats in this org return CIDs now.
