### ISSUE TITLE
What are the options in `resolver.tree()`?

### ISSUE THREAD

**Issue by mikeal** [ipld/interface-ipld-format#45]
I noticed that there's an optional options object here but it isn't document. What are the options and is there anything we need implementations to do with them?

**Comment by vmx** [comment]
It got recently removed, see https://github.com/ipld/interface-ipld-format/issues/39 for more information.

**Comment by mikeal** [comment]
Ok, great, we just need to remove it from the API definition in the table
of contents in the README :)
