### ISSUE TITLE
Proposal: Remove unnecessary async

### ISSUE THREAD

**Issue by achingbrain** [ipld/interface-ipld-format#54]
The `serialize/deserialize`/`encode/decode` methods are async (callback or promise depending on API version) but the APIs that do the actual work as exposed by (for example) [`protons`](https://www.npmjs.com/package/protons), [`pbf`](https://www.npmjs.com/package/pbf) and [`borc`](https://www.npmjs.com/package/borc) are synchronous.

The work @mcollina and Nearform did exposed artificially introduced asynchronous behaviour as a performance bottleneck of the IPFS/IPLD/libp2p codebases and something that should be removed, yet in the API rewrite these methods are still asynchronous.

Are there any IPLD formats that actually require asynchronicity to serialize/deserialize?

**Comment by mikeal** [comment]
I’ve wondered about this as well.

There’s a working assumption that codecs in the future may require async. Any codec that requires encryption for instance would have to be async in the browser. Most of how we talk about encryption is above the data model layer but there may be codecs for existing content addressed formats that require some kind of decryption or hashing to decode/encode.

Perhaps @daviddias or @Stebalien can fill us in on the history there.

**Comment by Stebalien** [comment]
Not sure. These are synchronous in go and are actually expected to be pure functions.

**Comment by daviddias** [comment]
There is a reason for this but one that can be reconsidered as it is mostly due to legacy.

When deserializing a `dag-pb` node, you get out an object with the CID computed right away. Calculating the CID requires the use of Crypto APIs, these Crypto APIs are Async in the Browser. Doing Sync in Node.js and Async in the Browser is not an option.

**Comment by mikeal** [comment]
I talked to @vmx about this today. We think it’s best to make the interface an async function but to move the implementations that aren’t async to just use sync methods. `await syncMethod()` doesn’t incur any overhead unless it’s the only reason you made the consuming function async, which is actually pretty unlikely, and when we move to `ipld-stack` the primary consumer will be the Block interface directly and those already have to be async because they do an async lookup of the codec implementation in order to support code splitting in the browser.

**Comment by achingbrain** [comment]
> await syncMethod() doesn’t incur any overhead

From my understanding when you `await` something (even a non-promise) a microtask is created, execution of which is deferred so a small amount of latency is introduced.

Ordinarily I wouldn't care about optimisations like this, but it's a very hot codepath.

**Comment by achingbrain** [comment]
> When deserializing a dag-pb node, you get out an object with the CID computed right away

The good news is this got pulled out a while back as it was a CPU bottleneck and because the calling code that starts the deserialization typically has the CID already as it's just used it to fetch the block.

**Comment by mikeal** [comment]
> From my understanding when you await something (even a non-promise) a microtask is created, execution of which is deferred so a small amount of latency is introduced.

Nope :) You can prove it pretty quickly in the repl.

```
> let synccall = () => console.log(2)
> let run = () => {
... let _run = async () => {
..... console.log(1)
..... await synccall()
..... }
... _run()
... console.log(3)
... }
> run()
1
2
3
```

It’s possible that the `await` call prevents inlining but that’s an optimization I would expect to see land if not already in V8 then in the near future and I don’t think it’s a good practice to program to vm optimizations that are likely to change, at least at this stage of the project.

**Comment by achingbrain** [comment]
My mistake, sorry - the promise itself is eagerly executed as your example shows, but any code `await`ing the result is deferred whether it's `await`ing a promise or not which will introduce latency.

Expanding the example to do something after the `await`ed sync call:

```javascript
let synccall = () => console.log(2)
let run = () => {
  let _run = async () => {
    console.log(1)
    await synccall()
    console.log(3)
  }
  _run()
  console.log(4)
}
run()
```

```
1
2
4
3
```

vs:

```javascript
let synccall = () => console.log(2)
let run = () => {
  let _run = async () => {
    console.log(1)
    synccall()
    console.log(3)
  }
  _run()
  console.log(4)
}
run()
```

```
1
2
3
4
```

**Comment by mikeal** [comment]
I see what is happening now. This is actually a really good guarantee, and
this can be optimized out if it's the last async thing you do, I wonder if
V8 does that or not.

Regardless, we can optimize this out ourselves in the new Block API by
checking if the return value is a promise and using the raw promise API if
it is.

**Comment by mikeal** [comment]
I’ve gone ahead and updated the `Block` library for the new IPLD stack to remove all unnecessary async but to still return a promise when such an interface is necessary.

The default [`encode`](https://github.com/ipld/js-ipld-stack/blob/master/src/block.js#L48) and `decode` methods on Block are still async as I think it would be hazardous for most consumers to mistakenly think the interface is synchronous when it only *mostly* operates that way, but I also expose [`encodeMaybeSync`](https://github.com/ipld/js-ipld-stack/blob/master/src/block.js#L51) and `decodeMaybeSync` from the internals. This means that

1. the default encode/decode path will factor out any unnecessary async underneath it, including the unnecessary async consuming a synchronous codec interface.
2. if `js-ipfs` wants to optimize its code in a similar way there are now methods exposed for that, and those interfaces still get all of the nice caching that is part of the new `Block` library.

This change introduced a lot of extra branching to code paths that I think will not be run all that often so I went ahead and updated the tests to hit 100% coverage just to make sure all these branches actually work.

I’ve updated the documentation for the `codec-interface` (which should be the next version of this repo) to reflect that [encode/decode methods](https://github.com/ipld/js-ipld-stack#encode--decode) in the interface can be either sync or async.

Does this sufficiently address the performance concerns?

**Comment by vmx** [comment]
I changed my mind for the current API. As I'm currently implementing it, I found out that it really makes sense to make `serialize()` and `deserialize()` *sync* calls. All out current format don't need async and I also tell people they shouldn't plan to much ahead into the future. As @mikeal is already working on the next generation API, I don't see a reason why we shouldn't stick to sync for now.

**Comment by mikeal** [comment]
@vmx I’m a little unclear on the decision and next steps here. Are you saying that the current `interface-ipld-format` will be changed to sync (it’s currently documented as async)?

The way I wrote this in `ipld-stack` was to support both sync and async and factor out the performance issues.

**Comment by vmx** [comment]
@mikeal Yes, I'll probably change the spec to have them sync. That decision is independent of the work you do in `ipld-stack`.

**Comment by vmx** [comment]
Done, `serialize()` and `deserialize()` are sync now.
