### ISSUE TITLE
utils.cid should uses the serialized dag node

### ISSUE THREAD

**Issue by wanderer** [ipld/interface-ipld-format#7]
can [utils.cid](https://github.com/ipld/interface-ipld-format#utilciddagnode-callback) take in the serialized dag node instead of the node it self?

#### `util.cid(serializedNode, callback)`

> get the CID of the serialized dagNode

`callback` must have the signature `function (err, cid)`, where `err` is an Error is the function fails and `cid` is a CID instance of the dagNode.

## Rational
Currently resolver.put need to serialize the data twice ([here](https://github.com/ipld/js-ipld-resolver/blob/master/src/index.js#L205) and [here](https://github.com/ipld/js-ipld-resolver/blob/master/src/index.js#L350)). This causes preformance overhead can lead to rather confusing bugs.

**Comment by daviddias** [comment]
Added to spec update proposal. Let's follow up on the discussion there -> https://github.com/ipld/interface-ipld-format/pull/11#discussion_r135392731
